# Generated by Django 4.2.3 on 2023-11-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CSEC_APP", "0003_events"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="members",
            options={"verbose_name_plural": "Members"},
        ),
        migrations.RemoveField(
            model_name="members",
            name="profile_image",
        ),
        migrations.AlterField(
            model_name="events",
            name="organizer",
            field=models.CharField(max_length=100),
        ),
    ]
